image: gradle:8.5-jdk17

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - gradle build -x test

test-job:
  stage: test
  script:
    - gradle test
  artifacts:
    when: always
    paths:
      - build/test-results/
    expire_in: 1 week

deploy-job:
  stage: deploy
  image: docker/compose:1.29.2
  services:
    - docker:dind
  script:
    - docker build -t media-service-image:0.0.1 .
    - docker-compose down
    - docker-compose up -d
  only:
    - main

